# **Importing Libraries**
---

In [1]:
from functions import extract_demands_institutions, extract_values_fuel_type, extract_insert_data, update_data_to_newest_datetime, extract_view_to_df

from dotenv import load_dotenv
import os

import datetime

# **Initialization**
---

In [18]:
load_dotenv()

api_key = os.getenv('EIA_API')
username_postgres = os.getenv('USERNAME_POSTGRES')
pw_postgres = os.getenv('PW_POSTGRES')

start = '2023-01-01T00'
end = (datetime.datetime.now() - datetime.timedelta(hours=10)).strftime('%Y-%m-%dT%H')
institutions = ["PJM", "CISO", "ERCO", "MISO", "SWPP"]

# **Extraction - Database Initialization & Storage to Database**
---

## **1. Electricity Demand**
---

In [19]:
df, path_df = extract_demands_institutions(start=start, end=end, api_key=api_key, institutions=institutions, folder_name='raw', max_workers=6)

Processing PJM: start - 2023-01-01T00, end - 2026-08-10T01
Processing CISO: start - 2023-01-01T00, end - 2026-08-10T01
Processing ERCO: start - 2023-01-01T00, end - 2026-08-10T01
Processing MISO: start - 2023-01-01T00, end - 2026-08-10T01
Processing SWPP: start - 2023-01-01T00, end - 2026-08-10T01
Total lines to process for SWPP: 31610
processed 5000 data points - SWPP
Total lines to process for CISO: 31610
processed 5000 data points - CISO
Total lines to process for PJM: 31609
processed 5000 data points - PJM
Total lines to process for MISO: 31610
processed 5000 data points - MISO
processed 10000 data points - SWPP
processed 10000 data points - CISO
processed 10000 data points - PJM
processed 10000 data points - MISO
processed 15000 data points - SWPP
processed 15000 data points - PJM
processed 15000 data points - CISO
processed 15000 data points - MISO
processed 20000 data points - SWPP
processed 20000 data points - CISO
processed 20000 data points - PJM
processed 20000 data points - MISO
processed 25000 data points - SWPP
Total lines to process for ERCO: 31610
processed 5000 data points - ERCO
processed 25000 data points - CISO
processed 25000 data points - PJM
processed 25000 data points - MISO
processed 30000 data points - SWPP
processed 10000 data points - ERCO
processed 30000 data points - CISO
processed 30000 data points - PJM
processed 30000 data points - MISO
processed 31610 data points - SWPP
processed 15000 data points - ERCO
processed 31610 data points - CISO
processed 31609 data points - PJM
processed 31610 data points - MISO
processed 20000 data points - ERCO
processed 25000 data points - ERCO
processed 30000 data points - ERCO
processed 31610 data points - ERCO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\raw\demand_raw.csv

In [20]:
for name in df['rto_name'].unique():
    print(f'Length of {name}: {len(df[df['rto_name'] == name])}')

display(df)

Length of SWPP: 31610
Length of CISO: 31610
Length of PJM: 31609
Length of MISO: 31610
Length of ERCO: 31610

,id_demand,time_stamp,rto_name,rto_full_name,demand_mwh
0,DERSWPP2023-01-01T00AW,2023-01-01T00,SWPP,Southwest Power Pool,28291
1,DERSWPP2023-01-01T01AW,2023-01-01T01,SWPP,Southwest Power Pool,28727
2,DERSWPP2023-01-01T02AW,2023-01-01T02,SWPP,Southwest Power Pool,28370
3,DERSWPP2023-01-01T03AW,2023-01-01T03,SWPP,Southwest Power Pool,27955
4,DERSWPP2023-01-01T04AW,2023-01-01T04,SWPP,Southwest Power Pool,27668
...,...,...,...,...,...
158044,DERERCO2026-08-09T21AW,2026-08-09T21,ERCO,"Electric Reliability Council of Texas, Inc.",83705
158045,DERERCO2026-08-09T22AW,2026-08-09T22,ERCO,"Electric Reliability Council of Texas, Inc.",84710
158046,DERERCO2026-08-09T23AW,2026-08-09T23,ERCO,"Electric Reliability Council of Texas, Inc.",84729
158047,DERERCO2026-08-10T00AW,2026-08-10T00,ERCO,"Electric Reliability Council of Texas, Inc.",83766
158048,DERERCO2026-08-10T01AW,2026-08-10T01,ERCO,"Electric Reliability Council of Texas, Inc.",81188

## **2. Fuel Type**
---

In [21]:
df_n, path_df_n = extract_values_fuel_type(start=start, end=end, api_key=api_key, institutions=institutions, folder_name='raw')

Processing PJM: start - 2023-01-01T00, end - 2026-08-10T01
Processing CISO: start - 2023-01-01T00, end - 2026-08-10T01
Processing ERCO: start - 2023-01-01T00, end - 2026-08-10T01
Processing MISO: start - 2023-01-01T00, end - 2026-08-10T01
Processing SWPP: start - 2023-01-01T00, end - 2026-08-10T01
Total lines to process for CISO: 258139
processed 5000 data points - CISO
Total lines to process for SWPP: 257166
processed 5000 data points - SWPP
Total lines to process for ERCO: 245838
processed 5000 data points - ERCO
Total lines to process for PJM: 252678
processed 5000 data points - PJM
Total lines to process for MISO: 234823
processed 5000 data points - MISO
processed 10000 data points - CISO
processed 10000 data points - ERCO
processed 10000 data points - PJM
processed 10000 data points - MISO
processed 10000 data points - SWPP
processed 15000 data points - CISO
processed 15000 data points - ERCO
processed 15000 data points - PJM
processed 15000 data points - SWPP
processed 15000 data points - MISO
processed 20000 data points - ERCO
processed 20000 data points - CISO
processed 20000 data points - PJM
processed 20000 data points - MISO
processed 20000 data points - SWPP
processed 25000 data points - ERCO
processed 25000 data points - PJM
processed 25000 data points - SWPP
processed 25000 data points - CISO
processed 25000 data points - MISO
processed 30000 data points - ERCO
processed 30000 data points - PJM
processed 30000 data points - CISO
processed 30000 data points - SWPP
processed 30000 data points - MISO
processed 35000 data points - ERCO
processed 35000 data points - SWPP
processed 35000 data points - PJM
processed 35000 data points - MISO
processed 35000 data points - CISO
processed 40000 data points - ERCO
processed 40000 data points - SWPP
processed 40000 data points - PJM
processed 40000 data points - MISO
processed 40000 data points - CISO
processed 45000 data points - ERCO
processed 45000 data points - SWPP
processed 45000 data points - PJM
processed 45000 data points - CISO
processed 45000 data points - MISO
processed 50000 data points - ERCO
processed 50000 data points - SWPP
processed 50000 data points - PJM
processed 50000 data points - CISO
processed 50000 data points - MISO
processed 55000 data points - ERCO
processed 55000 data points - SWPP
processed 55000 data points - PJM
processed 55000 data points - MISO
processed 55000 data points - CISO
processed 60000 data points - ERCO
processed 60000 data points - SWPP
processed 60000 data points - PJM
processed 60000 data points - MISO
processed 60000 data points - CISO
processed 65000 data points - ERCO
processed 65000 data points - SWPP
processed 65000 data points - MISO
processed 65000 data points - PJM
processed 65000 data points - CISO
processed 70000 data points - ERCO
processed 70000 data points - MISO
processed 70000 data points - PJM
processed 70000 data points - SWPP
processed 70000 data points - CISO
processed 75000 data points - ERCO
processed 75000 data points - PJM
processed 75000 data points - SWPP
processed 75000 data points - MISO
processed 75000 data points - CISO
processed 80000 data points - ERCO
processed 80000 data points - PJM
processed 80000 data points - SWPP
processed 80000 data points - MISO
processed 80000 data points - CISO
processed 85000 data points - ERCO
processed 85000 data points - PJM
processed 85000 data points - SWPP
processed 85000 data points - MISO
processed 90000 data points - SWPP
processed 90000 data points - PJM
processed 90000 data points - MISO
processed 95000 data points - PJM
processed 95000 data points - MISO
processed 100000 data points - PJM
processed 105000 data points - PJM
processed 85000 data points - CISO
processed 90000 data points - ERCO
processed 90000 data points - CISO
processed 110000 data points - PJM
processed 95000 data points - ERCO
processed 95000 data points - SWPP
processed 95000 data points - CISO
processed 115000 data points - PJM
processed 100000 data points - SWPP
processed 100000 data points - ERCO
processed 100000 data points - MISO
processed 120000 data points - PJM
processed 100000 data points - CISO
processed 105000 data points - SWPP
processed 105000 data points - ERCO
processed 125000 data points - PJM
processed 105000 data points - MISO
processed 105000 data points - CISO
processed 110000 data points - SWPP
processed 110000 data points - ERCO
processed 130000 data points - PJM
processed 110000 data points - MISO
processed 115000 data points - SWPP
processed 110000 data points - CISO
processed 115000 data points - ERCO
processed 135000 data points - PJM
processed 115000 data points - MISO
processed 120000 data points - SWPP
processed 115000 data points - CISO
processed 120000 data points - ERCO
processed 140000 data points - PJM
processed 125000 data points - SWPP
processed 120000 data points - MISO
processed 120000 data points - CISO
processed 125000 data points - ERCO
processed 145000 data points - PJM
processed 130000 data points - SWPP
processed 125000 data points - CISOprocessed 125000 data points - MISO

processed 130000 data points - ERCO
processed 150000 data points - PJM
processed 135000 data points - SWPP
processed 130000 data points - MISO
processed 130000 data points - CISO
processed 135000 data points - ERCO
processed 140000 data points - SWPP
processed 155000 data points - PJM
processed 135000 data points - MISO
processed 135000 data points - CISO
processed 140000 data points - ERCO
processed 160000 data points - PJM
processed 145000 data points - SWPP
processed 140000 data points - MISO
processed 140000 data points - CISO
processed 145000 data points - ERCO
processed 150000 data points - SWPP
processed 165000 data points - PJM
processed 145000 data points - MISO
processed 145000 data points - CISO
processed 150000 data points - ERCO
processed 155000 data points - SWPP
processed 170000 data points - PJM
processed 150000 data points - MISO
processed 150000 data points - CISO
processed 175000 data points - PJM
processed 155000 data points - ERCO
processed 160000 data points - SWPP
processed 155000 data points - MISO
processed 155000 data points - CISO
processed 180000 data points - PJM
processed 160000 data points - ERCO
processed 165000 data points - SWPP
processed 160000 data points - MISO
processed 160000 data points - CISO
processed 185000 data points - PJM
processed 165000 data points - ERCO
processed 165000 data points - MISO
processed 170000 data points - SWPP
processed 165000 data points - CISO
processed 170000 data points - ERCO
processed 190000 data points - PJM
processed 170000 data points - MISO
processed 175000 data points - SWPP
processed 170000 data points - CISO
processed 175000 data points - ERCO
processed 175000 data points - MISO
processed 195000 data points - PJM
processed 180000 data points - SWPP
processed 175000 data points - CISO
processed 180000 data points - MISO
processed 200000 data points - PJM
processed 180000 data points - ERCO
processed 185000 data points - SWPP
processed 180000 data points - CISO
processed 185000 data points - MISO
processed 185000 data points - ERCO
processed 205000 data points - PJM
processed 190000 data points - SWPP
processed 185000 data points - CISO
processed 190000 data points - MISO
processed 190000 data points - ERCO
processed 210000 data points - PJM
processed 195000 data points - SWPP
processed 190000 data points - CISO
processed 195000 data points - MISO
processed 195000 data points - ERCO
processed 215000 data points - PJM
processed 200000 data points - SWPP
processed 195000 data points - CISO
processed 200000 data points - MISO
processed 200000 data points - ERCO
processed 220000 data points - PJM
processed 205000 data points - SWPP
processed 200000 data points - CISO
processed 205000 data points - MISO
processed 205000 data points - ERCO
processed 205000 data points - CISO
processed 210000 data points - SWPP
processed 210000 data points - MISO
processed 225000 data points - PJM
processed 210000 data points - ERCO
processed 215000 data points - SWPP
processed 210000 data points - CISO
processed 215000 data points - MISO
processed 230000 data points - PJM
processed 215000 data points - ERCO
processed 220000 data points - SWPP
processed 215000 data points - CISO
processed 220000 data points - MISO
processed 235000 data points - PJM
processed 220000 data points - ERCO
processed 225000 data points - SWPP
processed 220000 data points - CISO
processed 225000 data points - MISO
processed 225000 data points - ERCO
processed 240000 data points - PJM
processed 230000 data points - SWPP
processed 225000 data points - CISO
processed 230000 data points - MISO
processed 230000 data points - ERCO
processed 245000 data points - PJM
processed 235000 data points - SWPP
processed 234823 data points - MISO
processed 235000 data points - ERCO
processed 240000 data points - SWPP
processed 240000 data points - ERCO
processed 245000 data points - SWPP
processed 245000 data points - ERCO
processed 250000 data points - SWPP
processed 230000 data points - CISO
processed 245838 data points - ERCO
processed 250000 data points - PJM
processed 255000 data points - SWPP
processed 235000 data points - CISO
processed 252678 data points - PJM
processed 257166 data points - SWPP
processed 240000 data points - CISO
processed 245000 data points - CISO
processed 250000 data points - CISO
processed 255000 data points - CISO
processed 258139 data points - CISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\raw\fueltype_raw.csv

In [22]:
df_n

,id_elec_generated,time_stamp,rto_name,rto_full_name,fuel_name,fuel_full_name,mwh_generated
0,FERMISOCOL2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",COL,Coal,26715
1,FERMISONG2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",NG,Natural Gas,21693
2,FERMISONUC2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",NUC,Nuclear,11167
3,FERMISOOTH2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",OTH,Other,1136
4,FERMISOSUN2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",SUN,Solar,1
...,...,...,...,...,...,...,...
1248639,FERCISOOIL2026-08-09T06AW,2026-08-09T06,CISO,California Independent System Operator,OIL,Petroleum,46
1248640,FERCISOOTH2026-08-09T06AW,2026-08-09T06,CISO,California Independent System Operator,OTH,Other,4745
1248641,FERCISOSUN2026-08-09T06AW,2026-08-09T06,CISO,California Independent System Operator,SUN,Solar,-62
1248642,FERCISOWAT2026-08-09T06AW,2026-08-09T06,CISO,California Independent System Operator,WAT,Hydro,4366
1248643,FERCISOWND2026-08-09T06AW,2026-08-09T06,CISO,California Independent System Operator,WND,Wind,4790

## **3. Storage to Database**
---

In [53]:
extract_insert_data(start=start, end=end, api_key=api_key, institutions=institutions, username_postgres=username_postgres, pw_postgres=pw_postgres, db_name='data_warehouse_electricity')

DB data_warehouse_electricity exists? False
Creating data_warehouse_electricity
DB data_warehouse_electricity exists? True
Processing PJM: start - 2023-01-01T00, end - 2026-08-06T03
Processing CISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing ERCO: start - 2023-01-01T00, end - 2026-08-06T03
Processing MISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing SWPP: start - 2023-01-01T00, end - 2026-08-06T03
Total lines to process for PJM: 31515
processed 5000 data points - PJM
Total lines to process for SWPP: 31516
processed 5000 data points - SWPP
Total lines to process for ERCO: 31516
processed 5000 data points - ERCO
Total lines to process for CISO: 31516
processed 5000 data points - CISO
Total lines to process for MISO: 31516
processed 5000 data points - MISO
processed 10000 data points - PJM
processed 10000 data points - ERCO
processed 10000 data points - SWPP
processed 10000 data points - CISO
processed 15000 data points - PJM
processed 10000 data points - MISO
processed 15000 data points - ERCO
processed 15000 data points - CISO
processed 15000 data points - SWPP
processed 20000 data points - PJM
processed 20000 data points - CISO
processed 20000 data points - SWPP
processed 25000 data points - PJM
processed 15000 data points - MISO
processed 20000 data points - ERCO
processed 30000 data points - PJM
processed 25000 data points - CISO
processed 25000 data points - SWPP
processed 20000 data points - MISO
processed 25000 data points - ERCO
processed 30000 data points - SWPP
processed 25000 data points - MISO
processed 31515 data points - PJM
processed 30000 data points - CISO
processed 30000 data points - ERCO
processed 30000 data points - MISO
processed 31516 data points - ERCO
processed 31516 data points - SWPP
processed 31516 data points - CISO
processed 31516 data points - MISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\raw\demand_raw.csv
Processing PJM: start - 2023-01-01T00, end - 2026-08-06T03
Processing CISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing ERCO: start - 2023-01-01T00, end - 2026-08-06T03
Processing MISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing SWPP: start - 2023-01-01T00, end - 2026-08-06T03
Total lines to process for CISO: 257275
processed 5000 data points - CISO
Total lines to process for MISO: 234055
processed 5000 data points - MISO
Total lines to process for SWPP: 256302
processed 5000 data points - SWPP
Total lines to process for PJM: 251910
processed 5000 data points - PJM
Total lines to process for ERCO: 245070
processed 5000 data points - ERCO
processed 10000 data points - MISO
processed 10000 data points - PJM
processed 10000 data points - SWPP
processed 10000 data points - ERCO
processed 10000 data points - CISO
processed 15000 data points - MISO
processed 15000 data points - PJM
processed 15000 data points - SWPP
processed 15000 data points - ERCO
processed 15000 data points - CISO
processed 20000 data points - PJM
processed 20000 data points - SWPP
processed 20000 data points - MISO
processed 25000 data points - PJM
processed 20000 data points - ERCO
processed 20000 data points - CISO
processed 25000 data points - SWPP
processed 25000 data points - MISO
processed 25000 data points - ERCO
processed 30000 data points - MISO
processed 30000 data points - PJM
processed 25000 data points - CISO
processed 30000 data points - SWPP
processed 30000 data points - ERCO
processed 35000 data points - MISO
processed 35000 data points - PJM
processed 30000 data points - CISO
processed 35000 data points - SWPP
processed 40000 data points - PJM
processed 35000 data points - ERCO
processed 35000 data points - CISO
processed 40000 data points - MISO
processed 40000 data points - SWPP
processed 40000 data points - CISO
processed 40000 data points - ERCO
processed 45000 data points - MISO
processed 45000 data points - PJM
processed 45000 data points - CISO
processed 45000 data points - SWPP
processed 50000 data points - PJM
processed 50000 data points - MISO
processed 45000 data points - ERCO
processed 50000 data points - SWPP
processed 55000 data points - PJM
processed 50000 data points - CISO
processed 55000 data points - MISO
processed 50000 data points - ERCO
processed 55000 data points - CISO
processed 55000 data points - SWPP
processed 60000 data points - MISO
processed 60000 data points - PJM
processed 55000 data points - ERCO
processed 60000 data points - CISO
processed 65000 data points - MISO
processed 65000 data points - PJM
processed 60000 data points - SWPP
processed 60000 data points - ERCO
processed 70000 data points - MISO
processed 65000 data points - CISO
processed 70000 data points - PJM
processed 65000 data points - SWPP
processed 75000 data points - MISO
processed 65000 data points - ERCO
processed 75000 data points - PJM
processed 70000 data points - CISO
processed 80000 data points - MISO
processed 70000 data points - SWPP
processed 70000 data points - ERCO
processed 80000 data points - PJM
processed 85000 data points - MISO
processed 75000 data points - SWPP
processed 75000 data points - ERCO
processed 75000 data points - CISO
processed 80000 data points - ERCO
processed 90000 data points - MISO
processed 80000 data points - CISO
processed 80000 data points - SWPP
processed 85000 data points - PJM
processed 95000 data points - MISO
processed 85000 data points - ERCO
processed 85000 data points - CISO
processed 85000 data points - SWPP
processed 90000 data points - PJM
processed 90000 data points - SWPP
processed 90000 data points - CISO
processed 95000 data points - PJM
processed 100000 data points - MISO
processed 90000 data points - ERCO
processed 95000 data points - SWPP
processed 105000 data points - MISO
processed 100000 data points - PJM
processed 95000 data points - ERCO
processed 95000 data points - CISO
processed 100000 data points - SWPP
processed 110000 data points - MISO
processed 100000 data points - ERCO
processed 100000 data points - CISO
processed 105000 data points - SWPP
processed 105000 data points - PJM
processed 115000 data points - MISO
processed 105000 data points - CISO
processed 110000 data points - PJM
processed 105000 data points - ERCO
processed 110000 data points - SWPP
processed 115000 data points - PJM
processed 120000 data points - MISO
processed 110000 data points - ERCO
processed 125000 data points - MISO
processed 115000 data points - ERCO
processed 115000 data points - SWPP
processed 120000 data points - PJM
processed 110000 data points - CISO
processed 130000 data points - MISO
processed 120000 data points - ERCO
processed 120000 data points - SWPP
processed 135000 data points - MISO
processed 125000 data points - PJM
processed 115000 data points - CISO
processed 125000 data points - ERCO
processed 125000 data points - SWPP
processed 120000 data points - CISO
processed 140000 data points - MISO
processed 130000 data points - PJM
processed 130000 data points - SWPP
processed 130000 data points - ERCO
processed 145000 data points - MISO
processed 135000 data points - PJM
processed 135000 data points - SWPP
processed 125000 data points - CISO
processed 140000 data points - PJM
processed 135000 data points - ERCO
processed 130000 data points - CISO
processed 150000 data points - MISO
processed 140000 data points - SWPP
processed 145000 data points - PJM
processed 135000 data points - CISO
processed 145000 data points - SWPP
processed 155000 data points - MISO
processed 140000 data points - ERCO
processed 150000 data points - PJM
processed 150000 data points - SWPP
processed 160000 data points - MISO
processed 140000 data points - CISO
processed 155000 data points - PJM
processed 155000 data points - SWPP
processed 145000 data points - ERCO
processed 165000 data points - MISO
processed 160000 data points - PJM
processed 150000 data points - ERCO
processed 145000 data points - CISO
processed 170000 data points - MISO
processed 175000 data points - MISO
processed 160000 data points - SWPP
processed 155000 data points - ERCO
processed 165000 data points - PJM
processed 150000 data points - CISO
processed 180000 data points - MISO
processed 165000 data points - SWPP
processed 160000 data points - ERCO
processed 155000 data points - CISO
processed 170000 data points - PJM
processed 170000 data points - SWPP
processed 185000 data points - MISO
processed 165000 data points - ERCO
processed 160000 data points - CISO
processed 175000 data points - PJM
processed 190000 data points - MISO
processed 170000 data points - ERCO
processed 165000 data points - CISO
processed 175000 data points - SWPP
processed 180000 data points - PJM
processed 170000 data points - CISO
processed 175000 data points - ERCO
processed 195000 data points - MISO
processed 180000 data points - SWPP
processed 185000 data points - PJM
processed 175000 data points - CISO
processed 180000 data points - ERCO
processed 200000 data points - MISO
processed 185000 data points - SWPP
processed 205000 data points - MISO
processed 190000 data points - PJM
processed 180000 data points - CISO
processed 185000 data points - ERCO
processed 190000 data points - SWPP
processed 210000 data points - MISO
processed 185000 data points - CISO
processed 195000 data points - PJM
processed 190000 data points - ERCO
processed 195000 data points - SWPP
processed 215000 data points - MISO
processed 200000 data points - PJM
processed 190000 data points - CISO
processed 200000 data points - SWPP
processed 195000 data points - ERCO
processed 205000 data points - SWPP
processed 220000 data points - MISO
processed 195000 data points - CISO
processed 200000 data points - ERCO
processed 225000 data points - MISO
processed 210000 data points - SWPP
processed 205000 data points - ERCO
processed 200000 data points - CISO
processed 230000 data points - MISO
processed 205000 data points - PJM
processed 215000 data points - SWPP
processed 210000 data points - ERCO
processed 205000 data points - CISO
processed 220000 data points - SWPP
processed 234055 data points - MISO
processed 210000 data points - PJM
processed 215000 data points - ERCO
processed 210000 data points - CISO
processed 225000 data points - SWPP
processed 215000 data points - PJM
processed 220000 data points - ERCO
processed 215000 data points - CISO
processed 230000 data points - SWPP
processed 220000 data points - PJM
processed 225000 data points - ERCO
processed 225000 data points - PJM
processed 220000 data points - CISO
processed 235000 data points - SWPP
processed 230000 data points - ERCO
processed 230000 data points - PJM
processed 235000 data points - ERCO
processed 240000 data points - SWPP
processed 225000 data points - CISO
processed 235000 data points - PJM
processed 240000 data points - ERCO
processed 230000 data points - CISO
processed 245000 data points - SWPP
processed 245000 data points - ERCO
processed 240000 data points - PJM
processed 250000 data points - SWPP
processed 245070 data points - ERCO
processed 245000 data points - PJM
processed 255000 data points - SWPP
processed 235000 data points - CISO
processed 240000 data points - CISO
processed 256302 data points - SWPP
processed 250000 data points - PJM
processed 245000 data points - CISO
processed 251910 data points - PJM
processed 250000 data points - CISO
processed 255000 data points - CISO
processed 257275 data points - CISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\raw\fueltype_raw.csv

Saved raw_rto_demand to database

Saved raw_fuel_electricity_generation to database
Inserted data to staging

# **Extraction - Most Recent Data**
---

In [9]:
load_dotenv()

api_key = os.getenv('EIA_API')
username_postgres = os.getenv('USERNAME_POSTGRES')
pw_postgres = os.getenv('PW_POSTGRES')

end_n = (datetime.datetime.now()).strftime('%Y-%m-%dT%H')
institutions = ["PJM", "CISO", "ERCO", "MISO", "SWPP"]
db_name = 'data_warehouse_electricity'

In [10]:
res = update_data_to_newest_datetime(api_key=api_key, username_postgres=username_postgres, pw_postgres=pw_postgres, db_name=db_name)

DB data_warehouse_electricity exists? True
Processing SWPP: start - 2026-08-09T03, end - 2026-08-10T11
Processing PJM: start - 2026-08-09T03, end - 2026-08-10T11
Processing MISO: start - 2026-08-09T03, end - 2026-08-10T11
Processing CISO: start - 2026-08-09T03, end - 2026-08-10T11
Processing ERCO: start - 2026-08-09T03, end - 2026-08-10T11
Total lines to process for ERCO: 25
processed 25 data points - ERCO
Total lines to process for SWPP: 25
processed 25 data points - SWPP
Total lines to process for CISO: 25
processed 25 data points - CISO
Total lines to process for MISO: 25
processed 25 data points - MISO
Total lines to process for PJM: 25
processed 25 data points - PJM
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\temp\demand_temp.csv
Processing SWPP: start - 2026-08-09T03, end - 2026-08-10T11
Processing PJM: start - 2026-08-09T03, end - 2026-08-10T11
Processing MISO: start - 2026-08-09T03, end - 2026-08-10T11
Processing CISO: start - 2026-08-09T03, end - 2026-08-10T11
Processing ERCO: start - 2026-08-09T03, end - 2026-08-10T11
Total lines to process for ERCO: 16
processed 16 data points - ERCO
Total lines to process for CISO: 36
processed 36 data points - CISO
Total lines to process for SWPP: 18
processed 18 data points - SWPP
Total lines to process for PJM: 8
processed 8 data points - PJM
Total lines to process for MISO: 16
processed 16 data points - MISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\temp\fueltype_temp.csv
Upserting to landing.raw_rto_demand
Finished upserting to landing - raw_rto_demand
Upserting to landing.raw_fuel_electricity_generation
Finished upserting to landing - raw_fuel_electricity_generation
Finished upserting data to staging
Finished updating materialized view

In [12]:
f, _ = res['raw_fuel_electricity_generation']
d, _ = res['raw_rto_demand']
f

,id_elec_generated,time_stamp,rto_name,rto_full_name,fuel_name,fuel_full_name,mwh_generated
0,FERERCOBAT2026-08-09T03AW,2026-08-09T03,ERCO,"Electric Reliability Council of Texas, Inc.",BAT,Battery storage,3827
1,FERERCOCOL2026-08-09T03AW,2026-08-09T03,ERCO,"Electric Reliability Council of Texas, Inc.",COL,Coal,10249
2,FERERCONG2026-08-09T03AW,2026-08-09T03,ERCO,"Electric Reliability Council of Texas, Inc.",NG,Natural Gas,39387
3,FERERCONUC2026-08-09T03AW,2026-08-09T03,ERCO,"Electric Reliability Council of Texas, Inc.",NUC,Nuclear,4947
4,FERERCOOTH2026-08-09T03AW,2026-08-09T03,ERCO,"Electric Reliability Council of Texas, Inc.",OTH,Other,80
...,...,...,...,...,...,...,...
89,FERMISONUC2026-08-09T04AW,2026-08-09T04,MISO,"Midcontinent Independent System Operator, Inc.",NUC,Nuclear,10381
90,FERMISOOTH2026-08-09T04AW,2026-08-09T04,MISO,"Midcontinent Independent System Operator, Inc.",OTH,Other,377
91,FERMISOSUN2026-08-09T04AW,2026-08-09T04,MISO,"Midcontinent Independent System Operator, Inc.",SUN,Solar,5
92,FERMISOWAT2026-08-09T04AW,2026-08-09T04,MISO,"Midcontinent Independent System Operator, Inc.",WAT,Hydro,543
93,FERMISOWND2026-08-09T04AW,2026-08-09T04,MISO,"Midcontinent Independent System Operator, Inc.",WND,Wind,10794

In [17]:
df_mlready, path_df_mlready = extract_view_to_df(username_postgres=username_postgres, pw_postgres=pw_postgres, db_name=db_name)
df_mlready

DB data_warehouse_electricity exists? True
c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\demand_electricty_generation_mlready.csv

,id_demand_elec_generated,time_stamp,rto_id,rto_full_name,demand_mwh,mwh_ng,mwh_nuc,mwh_wnd,mwh_sun,mwh_col,mwh_wat,mwh_oil,mwh_oth
0,DFCISO20230101-00AGG,2023-01-01 00:00:00,CISO,California Independent System Operator,24007,8897,2245,3395,954,4,2178,87,264
1,DFCISO20230101-01AGG,2023-01-01 01:00:00,CISO,California Independent System Operator,24546,9277,2247,3384,73,3,2455,87,846
2,DFCISO20230101-02AGG,2023-01-01 02:00:00,CISO,California Independent System Operator,25344,9394,2248,3236,-25,3,2696,82,1450
3,DFCISO20230101-03AGG,2023-01-01 03:00:00,CISO,California Independent System Operator,26468,9108,2247,3041,-25,3,2482,45,1307
4,DFCISO20230101-04AGG,2023-01-01 04:00:00,CISO,California Independent System Operator,26047,8969,2247,2748,-27,3,2303,45,1010
...,...,...,...,...,...,...,...,...,...,...,...,...,...
158054,DFSWPP20260809-23AGG,2026-08-09 23:00:00,SWPP,Southwest Power Pool,53502,None,None,None,None,None,None,None,None
158055,DFSWPP20260810-00AGG,2026-08-10 00:00:00,SWPP,Southwest Power Pool,52828,None,None,None,None,None,None,None,None
158056,DFSWPP20260810-01AGG,2026-08-10 01:00:00,SWPP,Southwest Power Pool,51269,None,None,None,None,None,None,None,None
158057,DFSWPP20260810-02AGG,2026-08-10 02:00:00,SWPP,Southwest Power Pool,49606,None,None,None,None,None,None,None,None
158058,DFSWPP20260810-03AGG,2026-08-10 03:00:00,SWPP,Southwest Power Pool,47821,None,None,None,None,None,None,None,None

In [15]:
path_df_mlready

'c:\\Users\\user\\works\\DE_studies\\electricity_demand_forecast\\data_processing\\data\\demand_electricty_generation_mlready.csv'