# **Importing Libraries**
---

In [51]:
from functions import extract_demands_institutions, extract_values_fuel_type, extract_insert_data, update_data_to_newest_datetime, extract_view_to_df

from dotenv import load_dotenv
import os

import datetime

# **Initialization**
---

In [52]:
load_dotenv()

api_key = os.getenv('EIA_API')
username_postgres = os.getenv('USERNAME_POSTGRES')
pw_postgres = os.getenv('PW_POSTGRES')

start = '2023-01-01T00'
end = (datetime.datetime.now() - datetime.timedelta(hours=10)).strftime('%Y-%m-%dT%H')
institutions = ["PJM", "CISO", "ERCO", "MISO", "SWPP"]

# **Extraction**
---

## **1. Electricity Demand**
---

In [75]:
df, path_df = extract_demands_institutions(start=start, end=end, api_key=api_key, institutions=institutions, folder_name='raw', max_workers=6)

Processing PJM: start - 2023-01-01T00, end - 2026-08-05T08
Processing CISO: start - 2023-01-01T00, end - 2026-08-05T08
Processing ERCO: start - 2023-01-01T00, end - 2026-08-05T08
Processing MISO: start - 2023-01-01T00, end - 2026-08-05T08
Processing SWPP: start - 2023-01-01T00, end - 2026-08-05T08
Total lines to process for ERCO: 31482
processed 5000 data points - ERCO
Total lines to process for SWPP: 31482
processed 5000 data points - SWPP
Total lines to process for MISO: 31482
processed 5000 data points - MISO
Total lines to process for CISO: 31482
processed 5000 data points - CISO
Total lines to process for PJM: 31481
processed 5000 data points - PJM
processed 10000 data points - ERCO
processed 10000 data points - SWPP
processed 10000 data points - MISO
processed 10000 data points - CISO
processed 10000 data points - PJM
processed 15000 data points - ERCO
processed 15000 data points - SWPP
processed 15000 data points - MISO
processed 15000 data points - CISO
processed 15000 data points - PJM
processed 20000 data points - ERCO
processed 20000 data points - SWPP
processed 20000 data points - CISO
processed 20000 data points - PJM
processed 20000 data points - MISO
processed 25000 data points - CISO
processed 25000 data points - SWPP
processed 25000 data points - ERCO
processed 25000 data points - PJM
processed 25000 data points - MISO
processed 30000 data points - CISO
processed 30000 data points - SWPP
processed 30000 data points - ERCO
processed 30000 data points - PJM
processed 30000 data points - MISO
processed 31482 data points - SWPP
processed 31482 data points - CISO
processed 31482 data points - ERCO
processed 31481 data points - PJM
processed 31482 data points - MISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data\raw\demand_raw.csv

In [76]:
for name in df['rto_name'].unique():
    print(f'Length of {name}: {len(df[df['rto_name'] == name])}')

display(df)

Length of SWPP: 31482
Length of CISO: 31482
Length of ERCO: 31482
Length of PJM: 31481
Length of MISO: 31482

,id_demand,time_stamp,rto_name,rto_full_name,demand_mwh
0,DERSWPP2023-01-01T00AW,2023-01-01T00,SWPP,Southwest Power Pool,28291
1,DERSWPP2023-01-01T01AW,2023-01-01T01,SWPP,Southwest Power Pool,28727
2,DERSWPP2023-01-01T02AW,2023-01-01T02,SWPP,Southwest Power Pool,28370
3,DERSWPP2023-01-01T03AW,2023-01-01T03,SWPP,Southwest Power Pool,27955
4,DERSWPP2023-01-01T04AW,2023-01-01T04,SWPP,Southwest Power Pool,27668
...,...,...,...,...,...
157404,DERMISO2026-08-04T13AW,2026-08-04T13,MISO,"Midcontinent Independent System Operator, Inc.",81664
157405,DERMISO2026-08-04T14AW,2026-08-04T14,MISO,"Midcontinent Independent System Operator, Inc.",85178
157406,DERMISO2026-08-04T15AW,2026-08-04T15,MISO,"Midcontinent Independent System Operator, Inc.",89273
157407,DERMISO2026-08-04T16AW,2026-08-04T16,MISO,"Midcontinent Independent System Operator, Inc.",93996
157408,DERMISO2026-08-04T17AW,2026-08-04T17,MISO,"Midcontinent Independent System Operator, Inc.",98507

## **2. Fuel Type**
---

In [78]:
df_n, path_df_n = extract_values_fuel_type(start=start, end=end, api_key=api_key, institutions=institutions, folder_name='raw')

Processing PJM: start - 2023-01-01T00, end - 2026-08-05T08
Processing CISO: start - 2023-01-01T00, end - 2026-08-05T08
Processing ERCO: start - 2023-01-01T00, end - 2026-08-05T08
Processing MISO: start - 2023-01-01T00, end - 2026-08-05T08
Processing SWPP: start - 2023-01-01T00, end - 2026-08-05T08
Total lines to process for ERCO: 244878
processed 5000 data points - ERCO
Total lines to process for SWPP: 256086
processed 5000 data points - SWPP
Total lines to process for MISO: 233863
processed 5000 data points - MISO
Total lines to process for CISO: 257059
processed 5000 data points - CISO
Total lines to process for PJM: 251718
processed 5000 data points - PJM
processed 10000 data points - ERCO
processed 10000 data points - MISO
processed 10000 data points - SWPP
processed 10000 data points - PJM
processed 10000 data points - CISO
processed 15000 data points - ERCO
processed 15000 data points - SWPP
processed 15000 data points - CISO
processed 15000 data points - MISO
processed 15000 data points - PJM
processed 20000 data points - ERCO
processed 20000 data points - MISO
processed 20000 data points - SWPP
processed 20000 data points - CISO
processed 20000 data points - PJM
processed 25000 data points - ERCO
processed 25000 data points - MISO
processed 25000 data points - SWPP
processed 25000 data points - CISO
processed 30000 data points - ERCO
processed 25000 data points - PJM
processed 30000 data points - SWPP
processed 30000 data points - MISO
processed 35000 data points - ERCO
processed 30000 data points - CISO
processed 30000 data points - PJM
processed 35000 data points - SWPP
processed 40000 data points - ERCO
processed 35000 data points - MISO
processed 35000 data points - CISO
processed 35000 data points - PJM
processed 40000 data points - SWPP
processed 45000 data points - ERCO
processed 40000 data points - CISO
processed 40000 data points - MISO
processed 40000 data points - PJM
processed 45000 data points - SWPP
processed 45000 data points - CISO
processed 50000 data points - ERCO
processed 45000 data points - MISO
processed 45000 data points - PJM
processed 50000 data points - SWPP
processed 50000 data points - CISO
processed 50000 data points - MISO
processed 55000 data points - ERCO
processed 50000 data points - PJM
processed 55000 data points - SWPP
processed 55000 data points - CISO
processed 55000 data points - MISO
processed 60000 data points - ERCO
processed 55000 data points - PJM
processed 60000 data points - SWPP
processed 60000 data points - CISO
processed 60000 data points - MISO
processed 65000 data points - ERCO
processed 60000 data points - PJM
processed 65000 data points - SWPP
processed 65000 data points - CISO
processed 65000 data points - MISO
processed 70000 data points - ERCO
processed 65000 data points - PJM
processed 70000 data points - SWPP
processed 70000 data points - CISO
processed 70000 data points - MISO
processed 75000 data points - ERCO
processed 70000 data points - PJM
processed 75000 data points - SWPP
processed 75000 data points - CISO
processed 80000 data points - ERCO
processed 75000 data points - MISO
processed 75000 data points - PJM
processed 80000 data points - SWPP
processed 80000 data points - CISO
processed 85000 data points - ERCO
processed 80000 data points - MISO
processed 80000 data points - PJM
processed 85000 data points - SWPP
processed 85000 data points - CISO
processed 90000 data points - ERCO
processed 85000 data points - MISO
processed 85000 data points - PJM
processed 90000 data points - SWPP
processed 90000 data points - CISO
processed 95000 data points - ERCO
processed 90000 data points - PJM
processed 90000 data points - MISO
processed 95000 data points - SWPP
processed 95000 data points - CISO
processed 95000 data points - PJM
processed 95000 data points - MISO
processed 100000 data points - ERCO
processed 100000 data points - SWPP
processed 100000 data points - CISO
processed 100000 data points - PJM
processed 105000 data points - ERCO
processed 100000 data points - MISO
processed 105000 data points - SWPP
processed 105000 data points - CISO
processed 105000 data points - PJM
processed 110000 data points - ERCO
processed 110000 data points - SWPP
processed 105000 data points - MISO
processed 110000 data points - CISO
processed 110000 data points - PJM
processed 110000 data points - MISO
processed 115000 data points - ERCO
processed 115000 data points - SWPP
processed 115000 data points - CISO
processed 115000 data points - PJM
processed 115000 data points - MISO
processed 120000 data points - SWPP
processed 120000 data points - CISO
processed 120000 data points - ERCO
processed 120000 data points - PJM
processed 120000 data points - MISO
processed 125000 data points - SWPP
processed 125000 data points - CISO
processed 125000 data points - ERCO
processed 125000 data points - PJM
processed 125000 data points - MISO
processed 130000 data points - SWPP
processed 130000 data points - CISO
processed 130000 data points - ERCO
processed 130000 data points - PJM
processed 135000 data points - CISO
processed 130000 data points - MISO
processed 135000 data points - SWPP
processed 135000 data points - ERCO
processed 135000 data points - PJM
processed 140000 data points - SWPP
processed 140000 data points - CISO
processed 135000 data points - MISO
processed 140000 data points - PJM
processed 140000 data points - ERCO
processed 145000 data points - CISO
processed 145000 data points - SWPP
processed 140000 data points - MISO
processed 145000 data points - PJM
processed 145000 data points - ERCO
processed 150000 data points - CISO
processed 150000 data points - SWPP
processed 145000 data points - MISO
processed 150000 data points - PJM
processed 150000 data points - ERCO
processed 155000 data points - CISO
processed 155000 data points - SWPP
processed 150000 data points - MISO
processed 155000 data points - ERCO
processed 160000 data points - CISO
processed 155000 data points - PJM
processed 160000 data points - SWPP
processed 155000 data points - MISO
processed 165000 data points - CISO
processed 160000 data points - ERCO
processed 160000 data points - PJM
processed 165000 data points - SWPP
processed 160000 data points - MISO
processed 170000 data points - CISO
processed 165000 data points - ERCO
processed 165000 data points - PJM
processed 170000 data points - SWPP
processed 165000 data points - MISO
processed 175000 data points - CISO
processed 170000 data points - ERCO
processed 175000 data points - SWPP
processed 170000 data points - PJM
processed 170000 data points - MISO
processed 180000 data points - CISO
processed 175000 data points - ERCO
processed 180000 data points - SWPP
processed 175000 data points - PJM
processed 175000 data points - MISO
processed 185000 data points - SWPP
processed 185000 data points - CISO
processed 180000 data points - ERCO
processed 180000 data points - PJM
processed 180000 data points - MISO
processed 190000 data points - CISO
processed 185000 data points - ERCO
processed 190000 data points - SWPP
processed 185000 data points - PJM
processed 185000 data points - MISO
processed 195000 data points - CISO
processed 195000 data points - SWPP
processed 190000 data points - ERCO
processed 190000 data points - PJM
processed 190000 data points - MISO
processed 200000 data points - CISO
processed 200000 data points - SWPP
processed 195000 data points - ERCO
processed 195000 data points - PJM
processed 195000 data points - MISO
processed 205000 data points - CISO
processed 205000 data points - SWPP
processed 200000 data points - ERCO
processed 200000 data points - PJM
processed 200000 data points - MISO
processed 210000 data points - CISO
processed 210000 data points - SWPP
processed 205000 data points - ERCO
processed 205000 data points - PJM
processed 205000 data points - MISO
processed 215000 data points - SWPP
processed 210000 data points - PJM
processed 210000 data points - ERCO
processed 210000 data points - MISO
processed 220000 data points - SWPP
processed 215000 data points - PJM
processed 215000 data points - ERCO
processed 215000 data points - MISO
processed 225000 data points - SWPP
processed 220000 data points - PJM
processed 220000 data points - ERCO
processed 220000 data points - MISO
processed 230000 data points - SWPP
processed 215000 data points - CISO
processed 225000 data points - ERCO
processed 225000 data points - PJM
processed 225000 data points - MISO
processed 235000 data points - SWPP
processed 220000 data points - CISO
processed 230000 data points - ERCO
processed 230000 data points - PJM
processed 230000 data points - MISO
processed 240000 data points - SWPP
processed 225000 data points - CISO
processed 235000 data points - PJM
processed 245000 data points - SWPP
processed 233863 data points - MISO
processed 235000 data points - ERCO
processed 230000 data points - CISO
processed 240000 data points - PJM
processed 250000 data points - SWPP
processed 240000 data points - ERCO
processed 235000 data points - CISO
processed 245000 data points - PJM
processed 255000 data points - SWPP
processed 240000 data points - CISO
processed 244878 data points - ERCO
processed 256086 data points - SWPP
processed 250000 data points - PJM
processed 245000 data points - CISO
processed 251718 data points - PJM
processed 250000 data points - CISO
processed 255000 data points - CISO
processed 257059 data points - CISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data\raw\fueltype_raw.csv

In [79]:
df_n

,id_elec_generated,time_stamp,rto_name,rto_full_name,fuel_name,fuel_full_name,mwh_generated
0,FERMISOCOL2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",COL,Coal,26715
1,FERMISONG2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",NG,Natural Gas,21693
2,FERMISONUC2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",NUC,Nuclear,11167
3,FERMISOOTH2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",OTH,Other,1136
4,FERMISOSUN2023-01-01T00AW,2023-01-01T00,MISO,"Midcontinent Independent System Operator, Inc.",SUN,Solar,1
...,...,...,...,...,...,...,...
1243599,FERCISOOIL2026-08-04T06AW,2026-08-04T06,CISO,California Independent System Operator,OIL,Petroleum,46
1243600,FERCISOOTH2026-08-04T06AW,2026-08-04T06,CISO,California Independent System Operator,OTH,Other,6107
1243601,FERCISOSUN2026-08-04T06AW,2026-08-04T06,CISO,California Independent System Operator,SUN,Solar,-62
1243602,FERCISOWAT2026-08-04T06AW,2026-08-04T06,CISO,California Independent System Operator,WAT,Hydro,4269
1243603,FERCISOWND2026-08-04T06AW,2026-08-04T06,CISO,California Independent System Operator,WND,Wind,5268

## **3. Storage to Database**
---

In [53]:
extract_insert_data(start=start, end=end, api_key=api_key, institutions=institutions, username_postgres=username_postgres, pw_postgres=pw_postgres, db_name='data_warehouse_electricity')

DB data_warehouse_electricity exists? False
Creating data_warehouse_electricity
DB data_warehouse_electricity exists? True
Processing PJM: start - 2023-01-01T00, end - 2026-08-06T03
Processing CISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing ERCO: start - 2023-01-01T00, end - 2026-08-06T03
Processing MISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing SWPP: start - 2023-01-01T00, end - 2026-08-06T03
Total lines to process for PJM: 31515
processed 5000 data points - PJM
Total lines to process for SWPP: 31516
processed 5000 data points - SWPP
Total lines to process for ERCO: 31516
processed 5000 data points - ERCO
Total lines to process for CISO: 31516
processed 5000 data points - CISO
Total lines to process for MISO: 31516
processed 5000 data points - MISO
processed 10000 data points - PJM
processed 10000 data points - ERCO
processed 10000 data points - SWPP
processed 10000 data points - CISO
processed 15000 data points - PJM
processed 10000 data points - MISO
processed 15000 data points - ERCO
processed 15000 data points - CISO
processed 15000 data points - SWPP
processed 20000 data points - PJM
processed 20000 data points - CISO
processed 20000 data points - SWPP
processed 25000 data points - PJM
processed 15000 data points - MISO
processed 20000 data points - ERCO
processed 30000 data points - PJM
processed 25000 data points - CISO
processed 25000 data points - SWPP
processed 20000 data points - MISO
processed 25000 data points - ERCO
processed 30000 data points - SWPP
processed 25000 data points - MISO
processed 31515 data points - PJM
processed 30000 data points - CISO
processed 30000 data points - ERCO
processed 30000 data points - MISO
processed 31516 data points - ERCO
processed 31516 data points - SWPP
processed 31516 data points - CISO
processed 31516 data points - MISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\raw\demand_raw.csv
Processing PJM: start - 2023-01-01T00, end - 2026-08-06T03
Processing CISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing ERCO: start - 2023-01-01T00, end - 2026-08-06T03
Processing MISO: start - 2023-01-01T00, end - 2026-08-06T03
Processing SWPP: start - 2023-01-01T00, end - 2026-08-06T03
Total lines to process for CISO: 257275
processed 5000 data points - CISO
Total lines to process for MISO: 234055
processed 5000 data points - MISO
Total lines to process for SWPP: 256302
processed 5000 data points - SWPP
Total lines to process for PJM: 251910
processed 5000 data points - PJM
Total lines to process for ERCO: 245070
processed 5000 data points - ERCO
processed 10000 data points - MISO
processed 10000 data points - PJM
processed 10000 data points - SWPP
processed 10000 data points - ERCO
processed 10000 data points - CISO
processed 15000 data points - MISO
processed 15000 data points - PJM
processed 15000 data points - SWPP
processed 15000 data points - ERCO
processed 15000 data points - CISO
processed 20000 data points - PJM
processed 20000 data points - SWPP
processed 20000 data points - MISO
processed 25000 data points - PJM
processed 20000 data points - ERCO
processed 20000 data points - CISO
processed 25000 data points - SWPP
processed 25000 data points - MISO
processed 25000 data points - ERCO
processed 30000 data points - MISO
processed 30000 data points - PJM
processed 25000 data points - CISO
processed 30000 data points - SWPP
processed 30000 data points - ERCO
processed 35000 data points - MISO
processed 35000 data points - PJM
processed 30000 data points - CISO
processed 35000 data points - SWPP
processed 40000 data points - PJM
processed 35000 data points - ERCO
processed 35000 data points - CISO
processed 40000 data points - MISO
processed 40000 data points - SWPP
processed 40000 data points - CISO
processed 40000 data points - ERCO
processed 45000 data points - MISO
processed 45000 data points - PJM
processed 45000 data points - CISO
processed 45000 data points - SWPP
processed 50000 data points - PJM
processed 50000 data points - MISO
processed 45000 data points - ERCO
processed 50000 data points - SWPP
processed 55000 data points - PJM
processed 50000 data points - CISO
processed 55000 data points - MISO
processed 50000 data points - ERCO
processed 55000 data points - CISO
processed 55000 data points - SWPP
processed 60000 data points - MISO
processed 60000 data points - PJM
processed 55000 data points - ERCO
processed 60000 data points - CISO
processed 65000 data points - MISO
processed 65000 data points - PJM
processed 60000 data points - SWPP
processed 60000 data points - ERCO
processed 70000 data points - MISO
processed 65000 data points - CISO
processed 70000 data points - PJM
processed 65000 data points - SWPP
processed 75000 data points - MISO
processed 65000 data points - ERCO
processed 75000 data points - PJM
processed 70000 data points - CISO
processed 80000 data points - MISO
processed 70000 data points - SWPP
processed 70000 data points - ERCO
processed 80000 data points - PJM
processed 85000 data points - MISO
processed 75000 data points - SWPP
processed 75000 data points - ERCO
processed 75000 data points - CISO
processed 80000 data points - ERCO
processed 90000 data points - MISO
processed 80000 data points - CISO
processed 80000 data points - SWPP
processed 85000 data points - PJM
processed 95000 data points - MISO
processed 85000 data points - ERCO
processed 85000 data points - CISO
processed 85000 data points - SWPP
processed 90000 data points - PJM
processed 90000 data points - SWPP
processed 90000 data points - CISO
processed 95000 data points - PJM
processed 100000 data points - MISO
processed 90000 data points - ERCO
processed 95000 data points - SWPP
processed 105000 data points - MISO
processed 100000 data points - PJM
processed 95000 data points - ERCO
processed 95000 data points - CISO
processed 100000 data points - SWPP
processed 110000 data points - MISO
processed 100000 data points - ERCO
processed 100000 data points - CISO
processed 105000 data points - SWPP
processed 105000 data points - PJM
processed 115000 data points - MISO
processed 105000 data points - CISO
processed 110000 data points - PJM
processed 105000 data points - ERCO
processed 110000 data points - SWPP
processed 115000 data points - PJM
processed 120000 data points - MISO
processed 110000 data points - ERCO
processed 125000 data points - MISO
processed 115000 data points - ERCO
processed 115000 data points - SWPP
processed 120000 data points - PJM
processed 110000 data points - CISO
processed 130000 data points - MISO
processed 120000 data points - ERCO
processed 120000 data points - SWPP
processed 135000 data points - MISO
processed 125000 data points - PJM
processed 115000 data points - CISO
processed 125000 data points - ERCO
processed 125000 data points - SWPP
processed 120000 data points - CISO
processed 140000 data points - MISO
processed 130000 data points - PJM
processed 130000 data points - SWPP
processed 130000 data points - ERCO
processed 145000 data points - MISO
processed 135000 data points - PJM
processed 135000 data points - SWPP
processed 125000 data points - CISO
processed 140000 data points - PJM
processed 135000 data points - ERCO
processed 130000 data points - CISO
processed 150000 data points - MISO
processed 140000 data points - SWPP
processed 145000 data points - PJM
processed 135000 data points - CISO
processed 145000 data points - SWPP
processed 155000 data points - MISO
processed 140000 data points - ERCO
processed 150000 data points - PJM
processed 150000 data points - SWPP
processed 160000 data points - MISO
processed 140000 data points - CISO
processed 155000 data points - PJM
processed 155000 data points - SWPP
processed 145000 data points - ERCO
processed 165000 data points - MISO
processed 160000 data points - PJM
processed 150000 data points - ERCO
processed 145000 data points - CISO
processed 170000 data points - MISO
processed 175000 data points - MISO
processed 160000 data points - SWPP
processed 155000 data points - ERCO
processed 165000 data points - PJM
processed 150000 data points - CISO
processed 180000 data points - MISO
processed 165000 data points - SWPP
processed 160000 data points - ERCO
processed 155000 data points - CISO
processed 170000 data points - PJM
processed 170000 data points - SWPP
processed 185000 data points - MISO
processed 165000 data points - ERCO
processed 160000 data points - CISO
processed 175000 data points - PJM
processed 190000 data points - MISO
processed 170000 data points - ERCO
processed 165000 data points - CISO
processed 175000 data points - SWPP
processed 180000 data points - PJM
processed 170000 data points - CISO
processed 175000 data points - ERCO
processed 195000 data points - MISO
processed 180000 data points - SWPP
processed 185000 data points - PJM
processed 175000 data points - CISO
processed 180000 data points - ERCO
processed 200000 data points - MISO
processed 185000 data points - SWPP
processed 205000 data points - MISO
processed 190000 data points - PJM
processed 180000 data points - CISO
processed 185000 data points - ERCO
processed 190000 data points - SWPP
processed 210000 data points - MISO
processed 185000 data points - CISO
processed 195000 data points - PJM
processed 190000 data points - ERCO
processed 195000 data points - SWPP
processed 215000 data points - MISO
processed 200000 data points - PJM
processed 190000 data points - CISO
processed 200000 data points - SWPP
processed 195000 data points - ERCO
processed 205000 data points - SWPP
processed 220000 data points - MISO
processed 195000 data points - CISO
processed 200000 data points - ERCO
processed 225000 data points - MISO
processed 210000 data points - SWPP
processed 205000 data points - ERCO
processed 200000 data points - CISO
processed 230000 data points - MISO
processed 205000 data points - PJM
processed 215000 data points - SWPP
processed 210000 data points - ERCO
processed 205000 data points - CISO
processed 220000 data points - SWPP
processed 234055 data points - MISO
processed 210000 data points - PJM
processed 215000 data points - ERCO
processed 210000 data points - CISO
processed 225000 data points - SWPP
processed 215000 data points - PJM
processed 220000 data points - ERCO
processed 215000 data points - CISO
processed 230000 data points - SWPP
processed 220000 data points - PJM
processed 225000 data points - ERCO
processed 225000 data points - PJM
processed 220000 data points - CISO
processed 235000 data points - SWPP
processed 230000 data points - ERCO
processed 230000 data points - PJM
processed 235000 data points - ERCO
processed 240000 data points - SWPP
processed 225000 data points - CISO
processed 235000 data points - PJM
processed 240000 data points - ERCO
processed 230000 data points - CISO
processed 245000 data points - SWPP
processed 245000 data points - ERCO
processed 240000 data points - PJM
processed 250000 data points - SWPP
processed 245070 data points - ERCO
processed 245000 data points - PJM
processed 255000 data points - SWPP
processed 235000 data points - CISO
processed 240000 data points - CISO
processed 256302 data points - SWPP
processed 250000 data points - PJM
processed 245000 data points - CISO
processed 251910 data points - PJM
processed 250000 data points - CISO
processed 255000 data points - CISO
processed 257275 data points - CISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\raw\fueltype_raw.csv

Saved raw_rto_demand to database

Saved raw_fuel_electricity_generation to database
Inserted data to staging

# **Extraction - Most Recent Data**
---

In [54]:
load_dotenv()

api_key = os.getenv('EIA_API')
username_postgres = os.getenv('USERNAME_POSTGRES')
pw_postgres = os.getenv('PW_POSTGRES')

end_n = (datetime.datetime.now()).strftime('%Y-%m-%dT%H')
institutions = ["PJM", "CISO", "ERCO", "MISO", "SWPP"]
db_name = 'data_warehouse_electricity'

In [55]:
res = update_data_to_newest_datetime(api_key=api_key, username_postgres=username_postgres, pw_postgres=pw_postgres, db_name=db_name)

DB data_warehouse_electricity exists? True
Processing CISO: start - 2026-08-05T03, end - 2026-08-06T13
Processing MISO: start - 2026-08-05T03, end - 2026-08-06T13
Processing PJM: start - 2026-08-05T03, end - 2026-08-06T13
Processing ERCO: start - 2026-08-05T03, end - 2026-08-06T13
Processing SWPP: start - 2026-08-05T03, end - 2026-08-06T13
Total lines to process for CISO: 27Total lines to process for MISO: 27
processed 27 data points - MISO
Total lines to process for SWPP: 27
processed 27 data points - SWPP
Total lines to process for ERCO: 27
processed 27 data points - ERCO

processed 27 data points - CISO
Total lines to process for PJM: 27
processed 27 data points - PJM
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\temp\demand_temp.csv
Processing CISO: start - 2026-08-05T03, end - 2026-08-06T13
Processing MISO: start - 2026-08-05T03, end - 2026-08-06T13
Processing PJM: start - 2026-08-05T03, end - 2026-08-06T13
Processing ERCO: start - 2026-08-05T03, end - 2026-08-06T13
Processing SWPP: start - 2026-08-05T03, end - 2026-08-06T13
Total lines to process for PJM: 8Total lines to process for SWPP: 18
processed 18 data points - SWPP

processed 8 data points - PJM
Total lines to process for ERCO: 16
processed 16 data points - ERCO
Total lines to process for CISO: 36
processed 36 data points - CISO
Total lines to process for MISO: 16
processed 16 data points - MISO
Saved results to c:\Users\user\works\DE_studies\electricity_demand_forecast\data_processing\data\temp\fueltype_temp.csv
Upserting to landing.raw_rto_demand
Finished upserting to landing - raw_rto_demand
Upserting to landing.raw_fuel_electricity_generation
Finished upserting to landing - raw_fuel_electricity_generation
Finished upserting data to staging
Finished updating materialized view

In [58]:
f, _ = res['raw_fuel_electricity_generation']
d, _ = res['raw_rto_demand']
d

,id_demand,time_stamp,rto_name,rto_full_name,demand_mwh
0,DERMISO2026-08-05T03AW,2026-08-05T03,MISO,"Midcontinent Independent System Operator, Inc.",93931
1,DERMISO2026-08-05T04AW,2026-08-05T04,MISO,"Midcontinent Independent System Operator, Inc.",88349
2,DERMISO2026-08-05T05AW,2026-08-05T05,MISO,"Midcontinent Independent System Operator, Inc.",83567
3,DERMISO2026-08-05T06AW,2026-08-05T06,MISO,"Midcontinent Independent System Operator, Inc.",80155
4,DERMISO2026-08-05T07AW,2026-08-05T07,MISO,"Midcontinent Independent System Operator, Inc.",76987
...,...,...,...,...,...
130,DERPJM2026-08-06T01AW,2026-08-06T01,PJM,"PJM Interconnection, LLC",129457
131,DERPJM2026-08-06T02AW,2026-08-06T02,PJM,"PJM Interconnection, LLC",125247
132,DERPJM2026-08-06T03AW,2026-08-06T03,PJM,"PJM Interconnection, LLC",118092
133,DERPJM2026-08-06T04AW,2026-08-06T04,PJM,"PJM Interconnection, LLC",112568
134,DERPJM2026-08-06T05AW,2026-08-06T05,PJM,"PJM Interconnection, LLC",107979

In [56]:
df_mlready, path_df_mlready = extract_view_to_df(username_postgres=username_postgres, pw_postgres=pw_postgres, db_name=db_name)
df_mlready

DB data_warehouse_electricity exists? True

,id_demand_elec_generated,time_stamp,rto_id,rto_full_name,demand_mwh,mwh_ng,mwh_nuc,mwh_wnd,mwh_sun,mwh_col,mwh_wat,mwh_oil,mwh_oth
0,DFCISO20230101-00AGG,2023-01-01 00:00:00,CISO,California Independent System Operator,24007,8897,2245,3395,954,4,2178,87,264
1,DFCISO20230101-01AGG,2023-01-01 01:00:00,CISO,California Independent System Operator,24546,9277,2247,3384,73,3,2455,87,846
2,DFCISO20230101-02AGG,2023-01-01 02:00:00,CISO,California Independent System Operator,25344,9394,2248,3236,-25,3,2696,82,1450
3,DFCISO20230101-03AGG,2023-01-01 03:00:00,CISO,California Independent System Operator,26468,9108,2247,3041,-25,3,2482,45,1307
4,DFCISO20230101-04AGG,2023-01-01 04:00:00,CISO,California Independent System Operator,26047,8969,2247,2748,-27,3,2303,45,1010
...,...,...,...,...,...,...,...,...,...,...,...,...,...
157584,DFSWPP20260806-01AGG,2026-08-06 01:00:00,SWPP,Southwest Power Pool,48632,None,None,None,None,None,None,None,None
157585,DFSWPP20260806-02AGG,2026-08-06 02:00:00,SWPP,Southwest Power Pool,47200,None,None,None,None,None,None,None,None
157586,DFSWPP20260806-03AGG,2026-08-06 03:00:00,SWPP,Southwest Power Pool,45633,None,None,None,None,None,None,None,None
157587,DFSWPP20260806-04AGG,2026-08-06 04:00:00,SWPP,Southwest Power Pool,43298,None,None,None,None,None,None,None,None
157588,DFSWPP20260806-05AGG,2026-08-06 05:00:00,SWPP,Southwest Power Pool,40851,None,None,None,None,None,None,None,None